### ISSUE TITLE
Release to rubygems.org as `rubocop-migration` gem

### ISSUE THREAD

**Issue by r7kamura** [r7kamura/rubocop-migration#1]
I'm thinking to release this gem on rubygems.org as `rubocop-migration` gem.

Since I want to use the department name `Migration/*`, I think it's natural to name this gem as `rubocop-migration`, but I found that a gem with the same name was created 5 years ago. After some investigation, the [repository](https://github.com/wealthsimple/rubocop-migration) has been archived and the development has already stopped. Perhaps, if we contact the authors, they may be able to give us the right to use the `rubocop-migration` gem name.

- https://github.com/wealthsimple/rubocop-migration
- https://rubygems.org/gems/rubocop-migration

**Comment by r7kamura** [comment]
@6 Hi pag. Please excuse me for contacting you suddenly, but I contacted you via this Issue in this repository because [wealthsimple/rubocop-migration](https://github.com/wealthsimple/rubocop-migration) was archived and I couldn't create an Issue there.

With the above background, if you don't mind, could you give me the rights to use the name `rubocop-migration` gem on rubygems.org? Since you have already released up to version 0.2.0, I promise to use 0.3.0 or higher versions in the future releases to avoid problems with the existing code.

I would be happy to add me [r7kamura](https://rubygems.org/profiles/r7kamura) as the owner of the [rubocop-migration gem ](https://rubygems.org/gems/rubocop-migration) on rubygems.org.

**Comment by 6** [comment]
@r7kamura done! Let me know if that works for you.

<img width="250" alt="Screen Shot 2022-10-19 at 11 57 50 AM" src="https://user-images.githubusercontent.com/158675/196743355-394bc870-da54-4b9c-9d61-38fe85b6c2de.png">

> Since you have already released up to version 0.2.0, I promise to use 0.3.0 or higher versions in the future releases to avoid problems with the existing code.

This would be great if you could start versioning at `0.3.0` - thank you.

**Comment by r7kamura** [comment]
@6 I've confirmed that I've successfully released the new version (rubocop-migration 0.3.2) to rubygems.org! 🎉 

- https://rubygems.org/gems/rubocop-migration
- https://rubygems.org/gems/rubocop-migration/versions/0.3.2

![image](https://user-images.githubusercontent.com/111689/196807126-3f8821e3-078b-4813-84a2-f2edc08a17d5.png)

Thank you so much for your help 👍
