### ISSUE TITLE
`Migration/AddIndexDuplicate` incompatible with `rubocop-rails >= 2.24.0`

### ISSUE THREAD

**Issue by klausmeyer** [r7kamura/rubocop-migration#19]
Hi,

thanks for this really nice library 👍 We've started to use it in our projects recently.

I've noticed that when using the latest version of `rubocop-rails` (2.24.1) the `Migration/AddIndexDuplicate` cop is no longer working:

```
An error occurred while Migration/AddIndexDuplicate cop was inspecting /Users/kmeyer/Code/innersource/dbs/foundation/service-dbs-configuration/db/migrate/20240405075909_create_schema_versions.rb:16:4.
wrong number of arguments (given 1, expected 2)
/Users/kmeyer/.rvm/gems/ruby-3.2.4@service-dbs-configuration/gems/rubocop-rails-2.24.1/lib/rubocop/rails/schema_loader.rb:15:in `load'
/Users/kmeyer/.rvm/gems/ruby-3.2.4@service-dbs-configuration/gems/rubocop-migration-0.5.0/lib/rubocop/cop/migration/add_index_duplicate.rb:140:in `schema'
/Users/kmeyer/.rvm/gems/ruby-3.2.4@service-dbs-configuration/gems/rubocop-migration-0.5.0/lib/rubocop/cop/migration/add_index_duplicate.rb:95:in `existing_indexes_for'
```

Reason seams to be a change in the method signature of `RuboCop::Rails::SchemaLoader.load`:

https://github.com/rubocop/rubocop-rails/commit/d8ce294ec9d5d7d9e2e2146143e582a975bbc24b#diff-bdce1eef83d707e6c7c22761506d4c06c9a5f5d269be5e13f249b2dba58d5153R15

Should I try to provide a PR addressing the issue?

**Comment by r7kamura** [comment]
Thanks, I was not aware of this issue.
It would be very helpful if you could create a pull request 👍

**Comment by klausmeyer** [comment]
I've pushed a first draft. Please have a look whenever you have time.
